name: Build, Test and SonarQube Scan

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-test-sonar:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_DB: auth_db
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install
        working-directory: api

      - name: Run tests
        env:
          DB_HOST: localhost
          DB_PORT: 5432
          DB_NAME: auth_db
          DB_USER: postgres
          DB_PASSWORD: postgres
          JWT_SECRET: supersecreto
        run: npm test
        working-directory: api

      - name: Setup Java (for Ant and Sonar Scanner)
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Run SonarQube analysis with Ant (build.xml)
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: ant -f build.xml sonar

